swagger: "2.0"
info:
  version: 0.0.1
  title: CRUD - Products
  description: Simple CRUD with products
  contact:
    name: Maradona Morais
    email: maradona.morais@hotmail.com
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT
host: 127.0.0.1:3000
basePath: /
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /product:
    get:
      summary: Retrieves all or one existing products
      parameters:
      - name: id
        in: query
        type: string
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/Product'
        400:
          description: Bad request. Responds with mongo's error
        404:
          description: Product not found
          examples:
            application/json:
              data: "The product was not found"
              error: true
definitions:
  Product:
    type: object
    properties:
      _id:
        type: string
        example: f63gfha674fg5kgjhnam
      name:
        type: string
        example: "Avengers: Endgame Ticket"
      price:
        type: number
        example: 18.0